---
abstract: 'Perl module that cleans up %ENV'
author:
  - 'Jonathan Yu <jawnsy@cpan.org>'
build_requires:
  Test::Builder::Tester: 0
  Test::NoWarnings: 0.084
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200000, CPAN::Meta::Converter version 2.101670'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Env-Sanctify-Auto
requires:
  Exporter: 5.57
  Module::Manifest: 0.07
  Test::Builder: 0.72
  Test::More: 0.62
  perl: 5.006
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Env-Sanctify-Auto
  homepage: http://search.cpan.org/dist/Env-Sanctify-Auto
  repository: git://github.com/jawnsy/Env-Sanctify-Auto.git
version: 1.002
