---
name: Env-Sanctify-Auto
version: 1.000000
author:
  - 'Jonathan Yu <frequency@cpan.org>'
abstract: Automatically clean up your %ENV
license: perl
resources:
  Ratings: http://cpanratings.perl.org/d/Env-Sanctify-Auto
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Env-Sanctify-Auto
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/Env-Sanctify-Auto
requires:
  Carp: 1.04
  perl: 5.006
  strict: 0
  version: 0.74
  warnings: 0
  Env::Sanctify: 0
build_requires:
  Test::More: 0
  Test::NoWarnings: 0.084
recommends:
  Perl::Critic: 1.096
  Test::Kwalitee: 1.01
  Test::MinimumVersion: 0.008
  Test::Perl::Critic: 1.01
  Test::Pod: 1.14
  Test::Pod::Coverage: 1.04
  Test::Portability::Files: 0.05
  Test::Signature: 1.1
  Test::YAML::Meta: 0.11
dynamic_config: 0
provides:
  Env::Sanctify::Auto:
    file: lib/Env/Sanctify/Auto.pm
    version: 1.000000
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
